### ISSUE TITLE
Cool，希望能在 v0.1.2 加入以下优化

### ISSUE THREAD

**Issue by shajiquan** [Houfeng/mditor#1]
谢谢分享。试用感受：
-  很简洁很大方；
-  分屏全屏很棒；
-  遗憾：没有快捷键，希望有，并且可以自定义；
-  遗憾：从 toolbar 点击插入代码后，ctrl+z 无法恢复到上一步；
-  遗憾：tab 可以缩进，但 shift+tab 无法取消缩进；
-  遗憾：`-`、`*`  无序列表及有序列表，按 enter 后下一行没有自动补全；

**Comment by Houfeng** [comment]
感谢您的建议，将会加入到下个版本。

**Comment by cshijiel** [comment]
粘贴/拖拽事件上传图片，可以配置接收URL，如果在加上这个功能真的太赞了~

**Comment by shajiquan** [comment]
希望我的需求得到满足后能在这里回复一下。我正好有个项目要用，但一直没有找到合适的，希望到时能用。

**Comment by Houfeng** [comment]
@cshijiel 
上传图片，就要涉及到服务端的接收，Mditor 目前没有计划内置图片上传相关的功能。但是 Mditor 可以很容易扩展新的功能，或替换现有工具条按钮的 “行为”。同时，有时间会提供一个包括图片上传的插件 (不会内置在 Mditor)。

**Comment by Houfeng** [comment]
@shajiquan 
请等待下个版本 ...

**Comment by shajiquan** [comment]
@Houfeng 查阅了一下 commits，发现您已经在优化了。涉及到一些我关心的点，再提一下建议啊：
1. 希望快捷键能支持自定义，在创建实例时指定对象来自定义；如果同时支持 mac 和 windows 的配置则更好了！
2. 希望能加入对 『 ` 』 语法的快捷键支持。

我自己改过一个 markdown 编辑器，是基于 ace editor 做的，支持的快捷键有：
- 链接：CMD + L
- 图片：Ctrl + I
- 行内代码 `：CMD+K
- 粗体：CMD+B
- 斜体：忘了……

想搞定但没搞好的：
- 代码块，三个 `：CMD+SHIFT+K

我平时主要用这些，所以我只做了这些，参照的是 mac 上一些编辑器的 key binding。供参考。

**Comment by shajiquan** [comment]
@Houfeng 另外建议优化到一定程度时可以适时地更新这个 demo http://houfeng.net/mditor/demo/index.html 这样我们可以更快更方便地看到更新效果。

谢谢！！！

**Comment by Houfeng** [comment]
@shajiquan 
0.1.2 已发布，您的建议大都已包含在本次更新中 (ctrl+z 的问题将延后处理)。
接下来，将会抽时间编写完整的 api 说明。

**Comment by shajiquan** [comment]
@Houfeng You are very Niubi！Let me test test.

**Comment by Houfeng** [comment]
@shajiquan  
默认的快捷键可能和您期望的不太一样，目前一致的都是 shift+alt+ “某键”，抱歉，但你可以通过 options.keymap 自定义，如:

``` javascript
var mditor = new Mditor("#editor",{
    keymap:{
        "bold":"ctrl+b"
    }
});
```

当然也可以用 `command+b` 或者 `{cmd}+b` ，`{cmd}` 在 windows 上会转换为 `ctrl`。  
另外，本次更新还包括一些其它的优化，比如，输入代码时的 `tab` 自动补全等

**Comment by shajiquan** [comment]
@Houfeng 快捷键和我期望的不一样，没关系，毕竟可以配置成我想要的。

我之所以建议您参考一些通用配置，是为了项目本身的上手、推广。比如，像 cmd+b/ ctrl+b 这样的快捷键很少被全局占用，在很多编辑器里它都是粗体的快捷键，我觉得没有必要重新定制——除非特殊情况，否则都可以参考比较通用的方案。

建议您考虑一下。

**Comment by shajiquan** [comment]
问题反馈：
1. 无序、有序列表的二级列表不会自动补全。
2. 有序列表时，如果有二级、三级列表，右侧的预览会把二级列表的编号改成罗马+英文字母方式表示（见下图）……建议就以 123 这种阿拉伯数字表示，直观、统一。
3. 才发现 tab 补全似乎是 8 个空格的宽度？这个宽度让人有割裂感。（个人希望变成 4 个空格，不仅是宽度是 4 个空格，内容也应该是空格而不是 tab。或者改成可配置？8 个感觉很奇怪……）

无论如何，谢谢跟进！！！

![image](https://cloud.githubusercontent.com/assets/3955959/10570207/1a67969a-7663-11e5-847b-cbb2fef97d52.png)

**Comment by Houfeng** [comment]
**1) 前两个问题**
下个版本，会尝试进一步优化

**2) Tab 缩进**
这是个 “常有讨论” 的问题（好像有一篇《缩进圣战》）。
Mditor 支持设定缩进格式，如下

``` javascript
var mditor = new Mditor('#editor');
mditor.INDENT="\t"; 
```

默认为 `\t`，可以设置为4个空格或8个空格。

**Comment by shajiquan** [comment]
@Houfeng 好，谢谢跟进。

刚瞄了一眼《缩进圣战》……有意思……我还是更喜欢 4 个空格的宽度。。。
