### ISSUE TITLE
请问不支持[TOC]这种自动创建目录的语法吗？

### ISSUE THREAD

**Issue by hezhongfeng** [Houfeng/mditor#12]
很感谢，已经在使用了
RT~

**Comment by Houfeng** [comment]
@hezhongfeng

目前不支持，可在下个版本尝试加入，同时欢迎您多提建议。

**Comment by hezhongfeng** [comment]
好的，谢谢回答。
感觉很好用，目前只知道这个语法不支持，一般的都够用了，以后发现什么还会继续反馈的。

**Comment by Houfeng** [comment]
@hezhongfeng 

谢谢，
我先将这个 issue 保持打开，等加入相关支持后再关闭。

**Comment by hezhongfeng** [comment]
好的~

**Comment by ifsmile** [comment]
这个可以通过marked的renderer.heading函数自己生成，我之前写过
