### ISSUE TITLE
Error: Cannot find module './parser'

### ISSUE THREAD

**Issue by hezhongfeng** [Houfeng/mditor#13]
在前端使用的时候发生这样的错误
这个错误是突然出现的，以前是正常的，不知道是否是我的问题
接着是这个错误
ReferenceError: Mditor is not defined，应该是上面那个引起的

**Comment by Houfeng** [comment]
@hezhongfeng

确保先引用了 mditor 了吗？能否在这里贴出更多的代码？

**Comment by hezhongfeng** [comment]
我自己的问题
解决了，谢谢
期待更新
