### ISSUE TITLE
gpcc install 

### ISSUE THREAD

**Issue by yourlei** [Houfeng/mditor#16]
# gpcc 安装记录

gpcc（Greenplum Command Center）是pivotal提供的Greenplum性能监控工具, 可监控各segment的状态、内存使用情况、磁盘io. 安装包可以在[这里](https://network.pivotal.io/products/pivotal-gpdb)下载

安装步骤：

1. 执行下面的命令，建立名为gpperfmon的数据库，默认使用gpmon用户
 ```[gpadmin@mdw ~]$ gpperfmon_install --enable --password gpmon --port 5432` ``

![1](https://cloud.githubusercontent.com/assets/11980288/21501139/3a7367e2-cc80-11e6-8719-53b8a09e59b2.jpg)

2. 重启数据库

`` `[gpadmin@mdw ~]$ gpstop -r` ``

![gpstop_log](https://cloud.githubusercontent.com/assets/11980288/21501363/3122ed50-cc82-11e6-9e62-8da31c1b7e63.jpg)

重启时报错，查看日志发现实pg_hba.conf文件配置出错，修改后就可以了

3. 查看gpmmon进程是否已经启动
`` `gpadmin@mdw ~]$ ps -ef | grep gpmmon| grep -v grep```

4 . 查看Performance Monitor数据库写入数据是否正常，检查是否有记录写入
```[gpadmin@mdw ~]$ psql -d gpperfmon -c 'select * from system_now'```

5. 如果配置了master的standby,拷贝Master主机拷贝配置文件到Standby Master的相应目录
```
[gpadmin@mdw ~]$ gpscp -h smdw /data/master/gpseg-1/pg_hba.conf =:$MASTER_DATA_DIRECTORY/
[gpadmin@mdw ~]$ gpscp -h smdw ~/.pgpass =:~/
```

6. 安装gpccc，注意是root用户
```
[root@mdw local]# unzip greenplum-cc-web-3.0.1-LINUX-x86_64.zip
[root@mdw local]# ./greenplum-cc-web-3.0.1-LINUX-x86_64.bin
[root@mdw local]# chown -R gpadmin:gpadmin /usr/local/greenplum-cc-web
[root@mdw local]# chown -R gpadmin:gpadmin /usr/local/greenplum-cc-web-3.0.1
```
7. 设置环境变量
```
[root@mdw local]# echo "source /usr/local/greenplum-cc-web-3.0.1/gpcc_path.sh" >>/home/gpadmin/.bashrc
[root@mdw ~]# echo "source /usr/local/greenplum-db-4.3.8.1/greenplum_path.sh" >>.bashrc 
[root@mdw ~]# source .bashrc
[root@mdw ~]# chmod 777 /usr/local/greenplum-cc-web-3.0.1/gpcc_path.sh
[root@mdw ~]# source /usr/local/greenplum-db/greenplum_path.sh
[root@mdw ~]# source /usr/local/greenplum-cc-web/gpcc_path.sh
```

8. 在所有主机安装GPCCC 

```
[root@mdw ~]# gpccinstall -f /home/gpadmin/conf/hostlist
```

9. 复制配置文件到其他节点主机
```
[gpadmin@mdw ~]$ gpscp -h sdw1 .bashrc =:~/
[gpadmin@mdw ~]$ gpscp -h sdw2 .bashrc =:~/
```
10.  配置安装详细项

`gpcmdr --setup `
```
   Please enter a new instance name:输入gpcc
   Is the master host for the Greenplum Database remote? Yy|Nn (default=N):n
   What would you like to use for the display name for this instance:gpcc
   What port does the Greenplum Database use? (default=5432):回车
   will you install workload manaager (default=N):Y
   What port would you like the web server to use for this instance?回车
   Do you want to enable SSL for the Web API Yy|Nn (default=N):n
   Do you want to copy the instance to a standby master host Yy|Nn (default=Y): 没有standby n
   What is the hostname of the standby master host? [mdw]:回车 
```

11. 启动实例
```gpcmdr --start gpcc```

12. 登录 ip:28080

**Comment by Houfeng** [comment]
这是啥？

**Comment by Junvn** [comment]
哪里可以找到gpccc的源码？
