### ISSUE TITLE
Cannot read property 'parse' of undefined

### ISSUE THREAD

**Issue by lys623** [Houfeng/mditor#2]
Cannot read property 'parse' of undefined

```
var mditor = require("mditor");
var parser = mditor.Parser();
```

**Comment by lys623** [comment]
有没destroy方法

**Comment by Houfeng** [comment]
少了 `new`

``` js
var parser = new mditor.Parser();
```

**Comment by leoskey** [comment]
我使用的0.1.4，node版本是0.12也有这个问题，第一个方法也没有解决这个问题

**Comment by Houfeng** [comment]
@leoskey 能否提供一些更为详细的信息？

**Comment by leoskey** [comment]
这次我使用了node 4.*，还是按照你的步骤。先在网页中引入css以及js文件，并new Editor，编辑器正常加载。然后在后端  
var mditor = require("mditor");  
var parser = mditor.Parser();  
使用parser.parse的时候报错   

var content = parser.parse(docs[0].report_detail);
                            ^
TypeError: Cannot read property 'parse' of undefined

**Comment by Houfeng** [comment]
抱歉，这个 issuse 前边的 comment 都有问题，可能误导你了，应该是

``` js
var parser = new mditor.Parser(opts);
```

关键是少了 `new`
