### ISSUE TITLE
undo+redo

### ISSUE THREAD

**Issue by liuhong1happy** [Houfeng/mditor#22]
是否能加入撤销和重做功能呐？

**Comment by Houfeng** [comment]
@liuhong1happy 
感谢您的建议，当前版本，没有对 undo/redo 做额外的处理，下个版本会做下专门处理

**Comment by Houfeng** [comment]
@liuhong1happy 
新版本已经有更好的 undo/redo 功能了，embed 和 desktop 版都有改一样的改进。

**Comment by Houfeng** [comment]
@liuhong1happy 
新版本发布，有更加完善的 undo/redo 功能了

**Comment by liuhong1happy** [comment]
@Houfeng 大赞
