### ISSUE TITLE
期待图片上传的功能

### ISSUE THREAD

**Issue by kazaff** [Houfeng/mditor#3]

**Comment by Houfeng** [comment]
Mditor 是一个 “单纯” 的 Markdown 编辑，其本身不会包含图片上传相关的东西。因为上传意味着服务端的接收，Mditor 不想去关注服务端是用什么语言编写、如何接收、保存等问题。

不过，Mditor 是很容易扩展的，比如 “替换默认 “图片” 按钮的功能使其弹出一个上传框，完成上传后将图片地址，通过 API 可以很方便的插入到文档光标所处位置”。那么接下来，如果时间允许我将写这么一个示例放到源码的 examples 目录。

谢谢您使用、以及建议。

**Comment by kazaff** [comment]
非常感谢，这就按照您说的去试着扩展一下，谢谢您开源这么好的项目

**Comment by Houfeng** [comment]
@kazaff 以下供参考:

替换原 image 按钮功能，最简单的方式是

``` javascript
mditor.cmd.image = function(){
    //your code 
};
```

在光标处插入文本:
~~//注意 insert 有拼写错误，这两天更新会修正这个问题~~
~~mditor.editor.insterBeforeText("some text");~~

``` javascript
//在光标处插入文本
mditor.editor.insertBeforeText("some text");
```

目前还没写较完整的说明，有什么问题可以随时，通过 GitHub 联系我。

**Comment by kazaff** [comment]
@Houfeng  收到～

**Comment by Houfeng** [comment]
@kazaff 
新版已修正 insert**\* 方法的拼写错误。
