### ISSUE TITLE
有没有相关的调试方法什么的？

### ISSUE THREAD

**Issue by JaxsonWang** [Houfeng/mditor#39]
我想把您的项目做成WordPress的插件，过程中发现如下问题：

![image](https://user-images.githubusercontent.com/16836692/34140311-c8504f1a-e4b4-11e7-838e-fe6c5f4600a9.png)

所以想问问有什么办法在控制台查看相关报错信息，谢谢！

**Comment by JaxsonWang** [comment]
![image](https://user-images.githubusercontent.com/16836692/34140409-74116ba4-e4b5-11e7-9a18-02cb1ec1449f.png)

**Comment by Houfeng** [comment]
能否提供更多的信息，比如浏览器及版本，并贴更多的代码，让我重现一下这个问题？

**Comment by JaxsonWang** [comment]
MacOS 10.13.12
Chrome 63.0.3239.84（正式版本）（64 位）

编辑器配置安装文档默认的配置：
```javascript
var mditor =  Mditor.fromTextarea(document.getElementById('wp-content-editor-container'));

//获取或设置编辑器的值
mditor.on('ready',function(){
        mditor.value = '** hello **';
        console.log(mditor.value);
});
```

FireFox Quantum 57.0.1 (64 位)：

![image](https://user-images.githubusercontent.com/16836692/34187661-80a3cdfe-e56d-11e7-9e8f-e64a9e233fb4.png)


```
TypeError: this.textarea is undefined

getValue  index.js:178:4
onReady/<  index.js:28:15
```

Safari 11.0.2 (13604.4.7.1.3)控制台报错如下：
```
TypeError: undefined is not an object (evaluating 'this.textarea.value')
```

**Comment by Houfeng** [comment]
@JaxsonWang 
ID 为 `wp-content-editor-container` 的 `textarea` 确实存在？并在 mditor 的初始化之前？

**Comment by JaxsonWang** [comment]
呃，是`textarea `？div不行吗？如果是这样的话，那的确麻烦多了

**Comment by Houfeng** [comment]
@JaxsonWang 
```js
var mditor = new Mditor();
// 挂载到指定的元素
mditor.$mount(document.body); 
```

这样也能创建 mditor 实例
