### ISSUE TITLE
ready事件和change事件进不去

### ISSUE THREAD

**Issue by WisestCoder** [Houfeng/mditor#47]
![image](https://user-images.githubusercontent.com/21785332/39340541-43f03944-4a01-11e8-9da5-e1328cbffe08.png)

问题如图，ready事件进不去

**Comment by JxSx** [comment]
我引用的CDN资源，和你出现的问题一样。换成dist目录下的本地文件可以了

**Comment by WisestCoder** [comment]
@JxSx 兄dei，dist和cdn道理是一样的，可能是版本不同，想问一下你用的版本是多少？贴个图

**Comment by WisestCoder** [comment]
@Houfeng 大神，怎么hack？
