### ISSUE TITLE
如何在ｔｅｘｔａｒｅａ中加入ｉｎｐｕｔ元素

### ISSUE THREAD

**Issue by yourlei** [Houfeng/mditor#5]
你好，我在ｎｏｄｅ项目中使用了Mditor，现在有个问题是我修改ｊｓ代码在 textarea元素中加入了一个input元素作为文章标题，执行后ｈｔｍｌ结构中有ｉｎｐｕｔ元素，但页面中却找不到，请问这个问题应该怎么解决．

**Comment by Houfeng** [comment]
在 textarea 中添加 input ?
